### PR TITLE
Run on Node 20.x

### PR DESCRIPTION
**Pull request by clechasseur**
- Use `@clechasseur/rs-actions-core` (tested on Node 20.x, more up-to-date dependencies)
- Use `@vercel/ncc` (build didn't work locally with the old tool)
- Update github-actions to use some that run on Node 20.x
- Use `.nvmrc` to setup node in github actions

Hello! GitHub has recently provided Node 20.x on action runners and is soon deprecating Node 16.x. This PR moves your github action to Node 20.x as well. I did not update the version number or changelog.

### CODE REVIEW

**Comment by clechasseur** [comment]
I wanted to update to the latest version of `@clechasseur/rs-actions-core`, but that didn't work well so I ended up updating all dependencies to recent versions. On the plus side, no more reported vulnerabilities 😄

**Comment by istellino-chub** [comment]
@clechasseur I really was looking into this when creating this issue https://github.com/rustsec/audit-check/issues/19

**Comment by clechasseur** [comment]
I've updated the PR after all to bring dependencies up-to-date. If anyone needs to, they can use this until this action is updated:

`clechasseur/rustsec-audit-check@b5ade62a8d38826bb50ca4b8b9bc2a8a97f0d44d`

**Comment by ross-paypay** [comment]
The fact that this PR has not been merged yet is a bit concerning. 😅 
What is blocking a merge and release?

Is this repository maintained?

**Comment by istellino-chub** [comment]
@tarcieri can we create a new release now that this is merged? so that it can be used by the people

**Pull request merged**
